#!/usr/bin/env python3
"""
PYNQ host for the GEMM HLS kernel — mirrors gemm_tb.sv.

Kernel: MatrixMultiplicationKernel  (ap_fixed<16,8>, MM_DYNAMIC_SIZES=ON)
Test  : A[N×K] × B[K×M] = C[N×M]
Input : chessboard pattern in ap_fixed<16,8>
          +1.0 = 0x0100 (= np.int16(256))  where (row+col)%2 == 0
          -1.0 = 0xFF00 (= np.int16(-256)) elsewhere
Output: C[i][j] = K × (-1)^(i+j)
          0x4000 (= +64×256) for K=64, even cells
          0xC000 (= -64×256) for K=64, odd  cells

Overlay requirement:
  The .bit and .hwh files must share the same stem and live in the same
  directory.  Pass either file; the other is found automatically by PYNQ.
  The IP block must be named MatrixMultiplication_0 in the block design.

Usage:
  python3 gemm_pynq.py design_gemm.bit
  python3 gemm_pynq.py design_gemm.bit --n 128 --k 64 --m 256
  python3 gemm_pynq.py design_gemm.bit --transposed-a --no-dump
"""

import argparse
import time
import numpy as np
import pynq
from pynq import allocate

# ── AXI-Lite control register byte offsets ────────────────────────────────
# Source: xmatrixmultiplicationkernel_hw.h  (generated by Vitis HLS)
OFF_AP_CTRL = 0x00   # [0]=ap_start  [1]=ap_done  [2]=ap_idle  [3]=ap_ready
OFF_A_LO    = 0x10   # pointer a — bits [31:0]
OFF_A_HI    = 0x14   # pointer a — bits [39:32]
OFF_B_LO    = 0x1C   # pointer b — bits [31:0]
OFF_B_HI    = 0x20   # pointer b — bits [39:32]
OFF_C_LO    = 0x28   # pointer c — bits [31:0]
OFF_C_HI    = 0x2C   # pointer c — bits [39:32]
OFF_SIZE_N  = 0x34   # size_n (MM_DYNAMIC_SIZES only)
OFF_SIZE_K  = 0x3C   # size_k
OFF_SIZE_M  = 0x44   # size_m
OFF_TRANS_A = 0x4C   # transposed_a (0 or 1)

# ── ap_fixed<16,8> encoding ───────────────────────────────────────────────
# Binary point between bits 7 and 8.  Float v → stored as int16(v * 256).
CHESS_POS = np.int16( 256)   # +1.0
CHESS_NEG = np.int16(-256)   # -1.0  (0xFF00 in two's-complement)


# ── Helpers ───────────────────────────────────────────────────────────────

def _chessboard(n_rows: int, n_cols: int) -> np.ndarray:
    """Return (n_rows, n_cols) int16 chessboard: CHESS_POS where (r+c)%2==0."""
    r = np.arange(n_rows, dtype=np.int32)[:, np.newaxis]
    c = np.arange(n_cols, dtype=np.int32)[np.newaxis, :]
    return np.where((r + c) % 2 == 0, CHESS_POS, CHESS_NEG).astype(np.int16)


def _verify(buf_c: np.ndarray, size_n: int, size_m: int, size_k: int) -> int:
    """Compare every C element against the expected chessboard output.
    Prints up to 10 mismatches.  Returns total mismatch count."""
    exp_even = np.int16( size_k * 256)
    exp_odd  = np.int16(-size_k * 256)
    r = np.arange(size_n, dtype=np.int32)[:, np.newaxis]
    c = np.arange(size_m, dtype=np.int32)[np.newaxis, :]
    expected = np.where((r + c) % 2 == 0, exp_even, exp_odd).astype(np.int16)

    bad_mask = buf_c != expected
    errors   = int(np.sum(bad_mask))
    if errors:
        rows, cols = np.where(bad_mask)
        for i in range(min(10, len(rows))):
            ri, ci = int(rows[i]), int(cols[i])
            print(f"  [SCB] MISMATCH C[{ri}][{ci}]: "
                  f"got 0x{buf_c[ri, ci] & 0xFFFF:04x}  "
                  f"expected 0x{expected[ri, ci] & 0xFFFF:04x}")
    return errors


def _dump(buf_c: np.ndarray, path: str) -> None:
    """Dump C to a text file — one 32-bit word per line in hex.
    Format matches the testbench $fdisplayh output so diff tools work."""
    flat32 = buf_c.view(np.uint32).flatten()
    with open(path, "w") as f:
        for w in flat32:
            f.write(f"{w:08x}\n")
    print(f"[MON] C dump → {path}")


# ── Main runner ───────────────────────────────────────────────────────────

def run(overlay_path: str,
        size_n: int, size_k: int, size_m: int,
        transposed_a: bool,
        verify: bool,
        dump: bool) -> bool:

    # ── Load overlay (requires .hwh alongside .bit) ──────────────────────
    print(f"[DRV] Loading overlay: {overlay_path}")
    ol  = pynq.Overlay(overlay_path)
    ip  = ol.MatrixMultiplication_0      # DefaultIP from .hwh

    # ── Allocate contiguous DDR buffers (int16 = ap_fixed<16,8>) ─────────
    print(f"[DRV] Allocating  "
          f"A[{size_n}×{size_k}]  B[{size_k}×{size_m}]  C[{size_n}×{size_m}]")
    buf_a = allocate(shape=(size_n, size_k), dtype=np.int16)
    buf_b = allocate(shape=(size_k, size_m), dtype=np.int16)
    buf_c = allocate(shape=(size_n, size_m), dtype=np.int16)

    # ── Fill A and B; pre-poison C with sentinel 0xDEAD ──────────────────
    print("[DRV] Filling A with chessboard ...")
    buf_a[:] = _chessboard(size_n, size_k)

    print("[DRV] Filling B with chessboard ...")
    buf_b[:] = _chessboard(size_k, size_m)

    # 0xDEAD as uint16 = 57005.  View cast lets us assign the raw bit pattern
    # without overflow into signed int16 (mirrors testbench poison_gap).
    print("[DRV] Pre-filling C with sentinel 0xDEAD ...")
    buf_c.view(np.uint16)[:] = 0xDEAD

    # Writeback CPU caches → DDR before the kernel can see the data
    buf_a.flush()
    buf_b.flush()
    buf_c.flush()

    phys_a = buf_a.physical_address
    phys_b = buf_b.physical_address
    phys_c = buf_c.physical_address
    print(f"[DRV] Physical  A=0x{phys_a:010x}  B=0x{phys_b:010x}  C=0x{phys_c:010x}")

    # ── Program AXI-Lite kernel registers ────────────────────────────────
    print("[DRV] Programming kernel registers ...")
    ip.write(OFF_A_LO,    phys_a & 0xFFFF_FFFF)
    ip.write(OFF_A_HI,    (phys_a >> 32) & 0xFF)
    ip.write(OFF_B_LO,    phys_b & 0xFFFF_FFFF)
    ip.write(OFF_B_HI,    (phys_b >> 32) & 0xFF)
    ip.write(OFF_C_LO,    phys_c & 0xFFFF_FFFF)
    ip.write(OFF_C_HI,    (phys_c >> 32) & 0xFF)
    ip.write(OFF_SIZE_N,  size_n)
    ip.write(OFF_SIZE_K,  size_k)
    ip.write(OFF_SIZE_M,  size_m)
    ip.write(OFF_TRANS_A, int(transposed_a))

    # ── Assert ap_start ───────────────────────────────────────────────────
    print("[DRV] Asserting ap_start ...")
    t0 = time.perf_counter()
    ip.write(OFF_AP_CTRL, 0x1)

    # ── Poll AP_CTRL[1] (ap_done) ─────────────────────────────────────────
    # AP_CTRL bits: [0]=ap_start  [1]=ap_done  [2]=ap_idle  [3]=ap_ready
    # ap_done is set by the kernel when it finishes and stays set until the
    # next ap_start write — no interrupt machinery (GIE/IER/ISR) needed.
    TIMEOUT_S = 30.0
    while not (ip.read(OFF_AP_CTRL) & 0x2):
        if time.perf_counter() - t0 > TIMEOUT_S:
            raise TimeoutError(f"Kernel did not complete within {TIMEOUT_S} s")
        time.sleep(0.001)

    elapsed_ms = (time.perf_counter() - t0) * 1e3
    ctrl = ip.read(OFF_AP_CTRL)
    print(f"[MON] Kernel complete in {elapsed_ms:.1f} ms  "
          f"(ap_done={bool(ctrl & 0x2)}  ap_idle={bool(ctrl & 0x4)})")

    # Invalidate CPU caches so we see the DDR data the kernel wrote
    buf_c.invalidate()

    # ── Optional file dump ────────────────────────────────────────────────
    if dump:
        _dump(buf_c, "matrix_c_result.bin")

    # ── Scoreboard ────────────────────────────────────────────────────────
    passed = True
    if verify:
        print(f"[SCB] Verifying C[{size_n}×{size_m}] ...")
        errors = _verify(buf_c, size_n, size_m, size_k)
        total  = size_n * size_m
        print("=" * 60)
        if errors == 0:
            print(f" TEST PASSED: all {total} C elements match chessboard pattern")
        else:
            print(f" TEST FAILED: {errors}/{total} mismatches")
            passed = False
        print("=" * 60)

    buf_a.freebuffer()
    buf_b.freebuffer()
    buf_c.freebuffer()
    return passed


# ── CLI ───────────────────────────────────────────────────────────────────

def main() -> None:
    p = argparse.ArgumentParser(
        description="PYNQ host for GEMM HLS kernel — mirrors gemm_tb.sv",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    p.add_argument("overlay",
                   help=".bit file (the .hwh must be in the same directory)")
    p.add_argument("--n",  type=int, default=128, metavar="N", help="Rows of A / C")
    p.add_argument("--k",  type=int, default=64,  metavar="K", help="Cols of A / rows of B")
    p.add_argument("--m",  type=int, default=256, metavar="M", help="Cols of B / C")
    p.add_argument("--transposed-a", action="store_true",
                   help="A is already stored column-major (MM_TRANSPOSED_A=ON)")
    p.add_argument("--no-verify", action="store_true",
                   help="Skip scoreboard verification")
    p.add_argument("--no-dump",   action="store_true",
                   help="Skip matrix_c_result.bin dump")
    args = p.parse_args()

    ok = run(args.overlay,
             size_n=args.n, size_k=args.k, size_m=args.m,
             transposed_a=args.transposed_a,
             verify=not args.no_verify,
             dump=not args.no_dump)
    raise SystemExit(0 if ok else 1)


if __name__ == "__main__":
    main()
